export function getStyles(isMobile, showControls) {
  return {
    modal: {
      position: 'fixed',
      inset: 0,
      background: '#000',
      zIndex: 1000,
      display: 'flex',
      flexDirection: 'column',
    },
    header: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: isMobile ? '12px 16px' : '16px 24px',
      background: 'linear-gradient(180deg, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.6) 60%, transparent 100%)',
      zIndex: 20,
      opacity: showControls ? 1 : 0,
      transition: 'opacity 0.3s ease',
      pointerEvents: showControls ? 'auto' : 'none',
    },
    headerLeft: {
      display: 'flex',
      alignItems: 'center',
      gap: '16px',
      minWidth: 0,
      flex: 1,
    },
    closeBtn: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '40px',
      height: '40px',
      border: 'none',
      borderRadius: '50%',
      background: 'rgba(255,255,255,0.1)',
      color: '#fff',
      cursor: 'pointer',
      transition: 'all 0.15s ease',
      flexShrink: 0,
    },
    titleContainer: {
      minWidth: 0,
      flex: 1,
    },
    title: {
      fontSize: isMobile ? '14px' : '16px',
      fontWeight: 600,
      color: '#fff',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      marginBottom: '2px',
    },
    creator: {
      fontSize: isMobile ? '12px' : '13px',
      color: 'rgba(255,255,255,0.7)',
    },
    headerRight: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      flexShrink: 0,
    },
    counter: {
      padding: '8px 16px',
      background: 'rgba(255,255,255,0.1)',
      borderRadius: '20px',
      fontSize: '13px',
      fontWeight: 500,
      color: 'rgba(255,255,255,0.9)',
    },
    content: {
      flex: 1,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    navButton: {
      position: 'absolute',
      top: '50%',
      transform: 'translateY(-50%)',
      width: isMobile ? '44px' : '52px',
      height: isMobile ? '44px' : '52px',
      border: 'none',
      borderRadius: '50%',
      background: 'rgba(255,255,255,0.1)',
      backdropFilter: 'blur(12px)',
      WebkitBackdropFilter: 'blur(12px)',
      color: '#fff',
      cursor: 'pointer',
      display: isMobile ? 'none' : 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 15,
      transition: 'all 0.2s ease',
      opacity: showControls ? 1 : 0,
      pointerEvents: showControls ? 'auto' : 'none',
    },
    navButtonDisabled: {
      opacity: 0.3,
      cursor: 'default',
    },
    footer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      background: 'linear-gradient(0deg, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.6) 60%, transparent 100%)',
      padding: isMobile ? '30px 16px 16px' : '40px 24px 20px',
      zIndex: 20,
      opacity: showControls ? 1 : 0,
      transition: 'opacity 0.3s ease',
      pointerEvents: showControls ? 'auto' : 'none',
    },
    statsRow: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: '0',
      flexWrap: isMobile ? 'wrap' : 'nowrap',
      gap: isMobile ? '8px' : '0',
    },
    stats: {
      display: 'flex',
      alignItems: 'center',
      gap: isMobile ? '12px' : '20px',
    },
    statItem: {
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
      fontSize: isMobile ? '12px' : '13px',
      color: 'rgba(255,255,255,0.8)',
    },
    shortcuts: {
      display: 'flex',
      alignItems: 'center',
      gap: '6px',
      fontSize: isMobile ? '11px' : '12px',
      color: 'rgba(255,255,255,0.5)',
    },
    shortcutKey: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: '20px',
      height: '20px',
      padding: '0 6px',
      background: 'rgba(255,255,255,0.15)',
      borderRadius: '4px',
      fontSize: '11px',
      fontWeight: 600,
      color: 'rgba(255,255,255,0.8)',
    },
  };
}
